namespace DataverseIntegration.Core;

using DataverseIntegration.CDS;
using DataverseIntegration.CRM;
using DataverseIntegration.FieldService;

permissionset 80000 "DVI Full"
{
    Assignable = true;
    Caption = 'Dataverse Integration Redesign - Full', Locked = true;

    Permissions =
        tabledata "DVI Setup" = RIMD,
        table "DVI Setup" = X,
        tabledata "DVI Follow-up Buffer" = RIMD,
        table "DVI Follow-up Buffer" = X,
        tabledata "DVI Option Value" = RIMD,
        table "DVI Option Value" = X,
        tabledata "DVI Mapping Assignment" = RIMD,
        table "DVI Mapping Assignment" = X,
        page "DVI Setup" = X,
        page "DVI Mapping Assignments" = X,
        tabledata "DVI Field Converter" = RIMD,
        table "DVI Field Converter" = X,
        page "DVI Field Converters" = X,
        codeunit "DVI Service Locator" = X,
        codeunit "DVI Feature Mgt." = X,
        codeunit "DVI App Area Subscriber" = X,
        codeunit "DVI Sync Context" = X,
        codeunit "DVI Runner Events" = X,
        codeunit "DVI Runner Dispatch" = X,
        codeunit "DVI Table Synch." = X,
        codeunit "DVI Record Synch." = X,
        codeunit "DVI Field Transfer" = X,
        codeunit "DVI Synch. Job Log" = X,
        codeunit "DVI Generic Handler" = X,
        codeunit "DVI Mapping Conflict Policy" = X,
        codeunit "DVI Dataverse Connection" = X,
        codeunit "DVI Mapping Logic" = X,
        codeunit "DVI Option Synch." = X,
        codeunit "DVI Coupling Runner" = X,
        codeunit "DVI Coupling Action" = X,
        codeunit "DVI Sales Connection" = X,
        codeunit "DVI Field Service Connection" = X,
        codeunit "DVI Mapping Resolver" = X,
        codeunit "DVI Coupling Store" = X,
        codeunit "DVI Config. Template Applier" = X,
        codeunit "DVI Integration Record Reader" = X,
        codeunit "DVI Follow-up Processor" = X,
        codeunit "DVI Completion Runner" = X,
        codeunit "DVI Standard Option Source" = X,
        codeunit "DVI Option Record Synch." = X,
        codeunit "DVI Option Coupling Store" = X,
        codeunit "DVI Default Assignment" = X,
        codeunit "DVI Record Action Context" = X,
        codeunit "DVI Record Mapping Resolver" = X,
        codeunit "DVI Standard Record Actions" = X,
        codeunit "DVI Record Actions" = X,
        codeunit "DVI UI Events" = X,
        codeunit "DVI Redirect" = X,
        codeunit "DVI Record Lookup" = X,
        codeunit "DVI Direct Converter" = X,
        codeunit "DVI Owner Converter" = X,
        codeunit "DVI Primary Contact Converter" = X,
        codeunit "DVI Currency Converter" = X,
        codeunit "DVI Unit of Measure Converter" = X,
        codeunit "DVI Option Value Converter" = X,
        codeunit "DVI Coupled Key Converter" = X,
        codeunit "DVI Converter Assignment" = X,
        codeunit "DVI Account Handler" = X,
        codeunit "DVI Contact Handler" = X,
        codeunit "DVI Currency Handler" = X,
        codeunit "DVI Salesperson Handler" = X,
        codeunit "DVI CDS Company" = X,
        codeunit "DVI CDS Relations" = X,
        codeunit "DVI Product Handler" = X,
        codeunit "DVI Unit Group Handler" = X,
        codeunit "DVI Unit Handler" = X,
        codeunit "DVI Price Level Handler" = X,
        codeunit "DVI Price Line Handler" = X,
        codeunit "DVI Opportunity Handler" = X,
        codeunit "DVI Sales Option Handler" = X,
        codeunit "DVI CRM Prices" = X,
        codeunit "DVI CRM Units" = X,
        codeunit "DVI Account Statistics" = X,
        codeunit "DVI Sales Order Handler" = X,
        codeunit "DVI Sales Order Line Handler" = X,
        codeunit "DVI Invoice Handler" = X,
        codeunit "DVI Invoice Line Handler" = X,
        codeunit "DVI CRM Sales Orders" = X,
        codeunit "DVI CRM Invoices" = X,
        codeunit "DVI Write-in Product Converter" = X,
        codeunit "DVI Bookable Resource Handler" = X,
        codeunit "DVI Customer Asset Handler" = X,
        codeunit "DVI Warehouse Handler" = X,
        codeunit "DVI Work Order Type Handler" = X,
        codeunit "DVI Project Task Handler" = X,
        codeunit "DVI FS Records" = X,
        codeunit "DVI Project Line Handler" = X,
        codeunit "DVI FS Projects" = X,
        codeunit "DVI FS Value Converter" = X,
        codeunit "DVI Work Order Handler" = X,
        codeunit "DVI Incident Handler" = X,
        codeunit "DVI Work Order Line Handler" = X,
        codeunit "DVI FS Service Orders" = X,
        codeunit "DVI FS Mapping Defaults" = X;
}
